---

- fail:
    msg: "service_id is required"
  when: service_id is not defined
  
- name: Get supervisorctl path
  shell: which supervisorctl
  register: supervisorctl_path


- name: supervisord add service
  shell: '{{ supervisorctl_path.stdout }} add {{ service_id }}'
  args:
    chdir: /etc/supervisor/conf.d
  become: true

- name: supervisord start service
  shell: '{{ supervisorctl_path.stdout }} start {{ service_id }}'
  args:
    chdir: /etc/supervisor/conf.d
  become: true


- name: supervisord add memmon{{ service_id }}
  shell: '{{ supervisorctl_path.stdout }} add memmon{{ service_id }}'
  args:
    chdir: /etc/supervisor/conf.d
  become: true

- name: supervisord start memmon{{ service_id }}
  shell: '{{ supervisorctl_path.stdout }} start memmon{{ service_id }}'
  args:
    chdir: /etc/supervisor/conf.d
  become: true

- include_tasks: cronjob.yml
