---

- name: Create tomcat user if not exist
  shell: "useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat"
  become: yes
  ignore_errors: yes

- name: Download
  shell: "wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz -P /tmp"

- name: Unpacking
  shell: "tar xf /tmp/apache-tomcat-9*.tar.gz -C /opt/tomcat"
  become: yes

- name: detect if tomcat latest link exist
  stat: 
    path: /opt/tomcat/latest
  become: yes
  register: tomcat_link

- name: Symlink
  shell: "ln -s /opt/tomcat/apache-tomcat-9.0.34 /opt/tomcat/latest"
  when: tomcat_link is not defined or tomcat_link.stat.islnk is not defined
  become: yes

- name: Chown
  shell: "chown -RH tomcat: /opt/tomcat/latest"
  become: yes

- name: Exec permission
  shell: "sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'"
  become: yes
